export default {
  SET_POST_TO_STORE: '@NEWS-FEEDS/SET_POST_TO_STORE',
  FETCH_POSTS: '@NEWS-FEEDS/FETCH_POSTS',
  REMOVE_POST: '@NEWS-FEEDS/REMOVE_POST',
  ADD_POST: '@NEWS-FEEDS/ADD_POST',
  UPDATE_POST: '@NEWS-FEEDS/UPDATE_POST',
};
